### ISSUE TITLE
Elevation is off bij 100m

### ISSUE THREAD

**Issue by Woodhousemelena** [andreynovikov/trekarta#92] opened 2019-11-05 12:03 UTC
Trekarta indicates that I am on 100m elevation. I assume that 0 is at sealevel, then my current elevation should be about 4 m. We can only wish to be at 100 m here in the Netherlands! ;-)

**Comment by Woodhousemelena** [comment] 2019-11-05 12:05
I see now that there is a bug report in Issue #76

**Comment by andreynovikov** [comment] 2019-11-05 12:17
Duplicate of #76

**Closed by andreynovikov** 2019-11-05 12:17 UTC

**Comment by hungerburg** [comment] 2019-11-13 22:08
Pasting coordinates of Den Haag into this form https://www.unavco.org/software/geodetic-utilities/geoid-height-calculator/geoid-height-calculator.html gives 100m correction against raw GPS readings.
