### ISSUE TITLE
Share a track is not working for phones without GMS (Huawei...)

### ISSUE THREAD

**Issue by jpiebrig** [andreynovikov/trekarta#226] opened 2023-12-31 08:30 UTC
Thanks a lot for your good job, I like Trekarta a lot and what follow is not a bug.
But it is only possible to export "Native" track. "GPX" and "KML" are not working for phones without GMS due to lack of them I think.
And I haven't find any solution to convert native tracks (.mtrack) to anything else.
Any solution will be appreciated ;-)

**Comment by andreynovikov** [comment] 2024-01-06 15:12
No it does not depend on GMS. What happens when you select GPX or KML format and press "Contnue" button?

**Comment by jpiebrig** [comment] 2024-01-07 15:14
Thank you a lot to worry about my probem ! 🙂

My phone is a Huawei Mate 40 Pro - NOH-NX9. No Google at all.
I join a video explaining my problem and what you ask. I write you also if you don't understand my very bad English :
https://www.grosfichiers.com/KYyyNwhQFda

I select the file to share and then select GPX format (with KML format it is the same). On the next screen I can choose the way to share the file. You can see that the GPX file seems to be there and the file size is about 200 ko.
I choose to share the file with e-mail - GMX mail - and you will see on the next screen that there is a black band saying that the file could not be join in attachment. Anyway, I try to send the mail but when I receive it, no attachment.
I have try to share the file in a lot of ways, Whatsapp, etc..., but it is the same : nothing.
I tried also, when I saw that there was a GPX file, to go in Android - data - mobi.maptrek - files - data but nothing in GPX. Nothing also in cache - export

**Comment by andreynovikov** [comment] 2024-01-08 17:59
Ok, I've got it. I have more questions:

1. After you press "Continue" and then see the list of apps can you find Trekarta (Trekarta import) in that list? If yes what happens if you choose it?
2. After you press "Continue" and then see the list of apps do not select anything, do not close Trekarta, but switch to your app launcher and run your file management app, go to _Android/data/mobi.maptrek/**cache**/export/_ - can you see created file there?

**Comment by jpiebrig** [comment] 2024-01-08 21:45
1. After I pressed "continue" I can see the list of Apps and Trekarta is among it. If I choose Trekarta a small window open where it is writed :    "Trekarta Import - Failed to get file".
2. After I pressed "continue", I go straight to Android/data/mobi.maptrek/cache/export/ with my explorer and /export/ is empty (I had done that a lot of time to see). But it seems to have had something a few time ago because under Export the date is :   "à l'instant" ("just now")

Have a look on the vidéo if you don'understand what I mean : 
https://www.grosfichiers.com/8a9GqLwjxN9

**Comment by andreynovikov** [comment] 2024-01-09 20:42
I see. Something is constantly removing files from cache. It's ether some excessive resource management phone settings or some third party application. Your cache directory is empty but it should contain many files:

![Screenshot_20240109_233526](https://github.com/andreynovikov/trekarta/assets/2943625/7c08b3ff-ce00-4137-8995-e410e33d6680)

At least there permanently should be the `mapIndex` file if you have ever downloaded any map.

**Comment by jpiebrig** [comment] 2024-01-10 09:44
I will try to find what this application or setting which causes this. I never had such strange behavior before. If I find I will tell you. Thanks a lot for your help.

**Comment by jpiebrig** [comment] 2024-01-10 13:37
I have an other phone, a Huawei Mate 30 Pro - LIO-L29. On this one I have the GMS installed (and not on the NOH-NX9, I didn't find how to...).
So I have just installed Trekarta on the LIO-L29, loaded a map and made a small track. And when I tried to export it, it is the same as for the NOH-NX9 : nothing in /export
I have changed some settings about cleaning the caches but noway.

**Comment by jpiebrig** [comment] 2024-01-10 14:08
Other curious thing. If I share a **native track**, when I push on the "continue" button and then without doing anything else in the application, I go straight to see /export with my explorer, it is the same there is nothing in it. But if I go back to the application and share again a native track, i can export it with mail, Whatsapp or others, and it works. So a .mtrack file can be shared, but not a .gpx or a .kml file.
And for the 3 formats there is nothing in /export after pushing "continue"

**Comment by andreynovikov** [comment] 2024-01-10 14:50
This is because native track is shared directly, not via `export` folder.

1. How do you install Trekarta on Huawei?
2. Are there any files in `cache` folder at all?
3. Can you see any files in  Android/data/mobi.maptrek/files with your file management app?

**Comment by andreynovikov** [comment] 2024-01-10 15:25
So there **are** other files in cache. Good news. Bad news is that I never remove files from cache. I will add logging to file so we can examine logs and will get back to this issue.

**Comment by andreynovikov** [comment] 2024-01-11 09:08
Please download apk from https://github.com/andreynovikov/trekarta/releases/tag/2024.01-alpha install it manually on test phone, run it as usual, try to export track and then close Trekarta normally. Then go to Android/data/mobi.maptrek/cache/export/ and find `debug.log` there. Please attach it here.

**Comment by andreynovikov** [comment] 2024-01-12 11:47
Thank you for your efforts. After analyzing the log I've found a place where the problem occurs. Now I have to understand the cause of that problem. I have added more logging and uploaded new APK. Can you please download and install it (same link), repeat all the steps and attach new log file.

**Comment by jpiebrig** [comment] 2024-01-12 16:05
I have uninstalled the previous beta version and installed the new one. Then I put a mtrack into Android/data/mobi.maptrek/files/data/ and try to export it. And it works !  Here are the files which where in /export
[debug.log](https://github.com/andreynovikov/trekarta/files/13921216/debug.log)
[exception.txt](https://github.com/andreynovikov/trekarta/files/13921217/exception.txt)
[mer. 3 janv. 2024, 13_32 – 15_18.txt](https://github.com/andreynovikov/trekarta/files/13921228/mer.3.janv.2024.13_32.15_18.txt)
you must rename the last .txt in gpx
Great !

**Comment by jpiebrig** [comment] 2024-01-12 18:44
I have triedwith the other Huawei (Huawei Mate 30 Pro and export is working also. I can send the gpx file by mail

**Comment by andreynovikov** [comment] 2024-01-13 16:53
Can you attach debug.log and exception.txt after crash?

**Comment by jpiebrig** [comment] 2024-01-13 21:54
Most of the time Trekarta crashes as soon I press "continue" after choosing the track. But the track is still there and usable. I join the 2 files :
[debug.log](https://github.com/andreynovikov/trekarta/files/13929594/debug.log)
[exception.txt](https://github.com/andreynovikov/trekarta/files/13929595/exception.txt)

**Comment by andreynovikov** [comment] 2024-01-18 11:57
I have completely replaced export module in latest version (2024.01), please try it and report any problems.

**Comment by jpiebrig** [comment] 2024-01-18 13:31
I cannot install the new version because it only on Google Play Store and I don't have it... I have try to install it on the Huawei Mate 30 Pro and extract the APK to install it on the Huawei Mate 40 Pro, but it doesn't work.

**Comment by jpiebrig** [comment] 2024-01-18 13:36
I just try it on the Mate 30 Pro which has GMS and it seems to work. Need to do more tests

**Comment by andreynovikov** [comment] 2024-01-18 13:48
It will be automatically published on F-Droid soon

**Comment by andreynovikov** [comment] 2024-01-18 16:47
BTW, are you a native french speaker? May be you can help localize Trekarta?

**Comment by jpiebrig** [comment] 2024-01-18 18:32
Yes, I am french. What do you mean by localize, translate ? --Envoyé à partir d’un Smartphone Android avec GMX Mail.Le 18/01/2024, 17:47 Andrey Novikov ***@***.***> a écrit:

   
  BTW, are you a native french speaker? May be you can help localize Trekarta?

**Comment by jpiebrig** [comment] 2024-01-18 20:49
Yes, I am french and even if I don't speak English very well, I can try to translate. But I don't know how to do.

**Comment by jpiebrig** [comment] 2024-01-22 19:05
It seems that export is working now without problem with the last version. Great.

**Comment by andreynovikov** [comment] 2024-01-24 20:08
I have created translation instructions: https://github.com/andreynovikov/trekarta/wiki/Translation
There's also a link to online tool for translation.

**Comment by jpiebrig** [comment] 2024-01-25 19:00
Hi Andrey, I have translated quite a lot of all the strings (with the help of a traductor, but not too much) but I don't succeed to translate app..values/plurals.xml (master) because I cannot save the translation. It tell me : Saisissez tous les pluriels afin de poursuivre (put all the plurals before going on). I don't know what to do. But I think that with that I have trans lated you can make a try.

**Comment by jpiebrig** [comment] 2024-01-26 10:57
Hi Andrew. I have done all the translation with Transifex and I think it is not too bad :) ! You can try the french version now and I will check.

**Comment by andreynovikov** [comment] 2024-01-26 11:51
Thank you! I'll close this issue, you may monitor progress here: https://github.com/andreynovikov/trekarta/pull/232

**Closed by andreynovikov** 2024-01-26 11:51 UTC
Labels: bug
